spring.application.name=demo

spring.liquibase.change-log=classpath:liquibase/database-changelog.yml

spring.datasource.url=jdbc:postgresql://localhost:5432/todo
spring.datasource.password=todo
spring.datasource.username=todo
